apiVersion: v1
kind: Service
metadata:
  name: frontend-student{{ STDID }}
spec:
  ports:
   - port: 3000
     name: http-fe
     protocol: TCP
     targetPort: 3000
  selector:
      app: frontend-student{{ STDID }}
  #type: LoadBalancer
  type: NodePort
