apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorCluster"
metadata: 
  name: "jupyter-notebook-student{{ STDID }}"
  labels: 
    description: ""
spec: 
  app: "jupyter-notebook"
  namingScheme: "CrNameRole"
  appCatalog: "local"
  connections: 
    #clusters: 
      #- "training-engine-shared"
    secrets: 
      - sc-secret-ai101-student{{ STDID }}
      - kc-secret-ai101-student{{ STDID }}
      - hpecp-ext-auth-secret
  roles: 
    - 
      id: "controller"
      members: 1
      serviceAccountName: "ecp-tenant-member-sa"
      resources: 
        requests: 
          cpu: "2"
          memory: "4Gi"
          nvidia.com/gpu: "0"
        limits: 
          cpu: "2"
          memory: "4Gi"
          nvidia.com/gpu: "0"
      #Note: "if the application is based on hadoop3 e.g. using StreamCapabilities interface, then change the below dtap label to 'hadoop3', otherwise for most applications use the default 'hadoop2'"
      #podLabels: 
        #hpecp.hpe.com/dtap: "hadoop2"