description: notebook-student{{ STDID }}
resources:
  slots: 0
bind_mounts:
  - host_path: /opt/bluedata/mapr/mnt/dfclusta.etc.fr.comm.hpecorp.net/exthcp/tenant-13/fsmount/checkpoints
    container_path: /determined_shared_fs
idle_timeout: 30m
