apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorCluster"
metadata: 
  name: "mlops-jupyter-notebook-student{{ STDID }}"
  labels: 
    description: ""
spec: 
  app: "jupyter-notebook"
  namingScheme: "CrNameRole"
  appCatalog: "local"
  connections: 
    clusters: 
      - training-engine-shared
    secrets: 
      - kc-secret-mlops-student{{ STDID }}
      - sc-secret-mlops-student{{ STDID }}
      - hpecp-ext-auth-secret
  roles: 
    - 
      id: "controller"
      members: 1
      serviceAccountName: "ecp-tenant-member-sa"
      resources: 
        requests: 
          cpu: "1"
          memory: "2Gi"
          nvidia.com/gpu: "0"
        limits: 
          cpu: "1"
          memory: "2Gi"
          nvidia.com/gpu: "0"
      #Note: "if the application is based on hadoop3 e.g. using StreamCapabilities interface, then change the below dtap label to 'hadoop3', otherwise for most applications use the default 'hadoop2'"
      #podLabels: 
        #hpecp.hpe.com/dtap: "hadoop2"