---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-nfs-pvc
  annotations:
    csi.hpe.com/nfsResources: "true"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  storageClassName: hpe-standard
