---
apiVersion: batch/v1
kind: Job
metadata:
  name: my-override-job
spec:
  template:
    spec:
      containers:
      - name: dd
        image: hpestorage/ioping
        command: [ "dd" ]
        args: [ "if=/dev/xvda", "of=/dev/null", "iflag=direct", "bs=32k" ]
        volumeDevices:
          - name: my-data
            devicePath: /dev/xvda
      volumes:
      - name: my-data
        persistentVolumeClaim:
          claimName: my-override-pvc
      restartPolicy: Never
  backoffLimit: 4
