apiVersion: v1
kind: Service
metadata:
  name: backend-envoy-student{{ STDID }}
spec:
  clusterIP: None
  ports:
   - port: 9001
     protocol: TCP
     targetPort: 9001
  selector:
      app: backend-student{{ STDID }}
